package restApi.model;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="role")
public class Role {
	@Id
	@Column(columnDefinition="INT")
	private int id;

	@Basic
	@Column(nullable=false, length=64)
	private String role;

	@OneToMany(targetEntity=restApi.model.User.class, mappedBy="role", cascade=CascadeType.MERGE)
	private Set<User> users = new HashSet<User>();


	public Role() {
	}

	public Role(int id) {
		this.id = id;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Set<User> getUsers() {
		return users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}
}