package restApi.model;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name = "user")
public class User {
	@Basic
	@Column(nullable = false, length = 128)
	private String email;

	@Basic
	private boolean enabled;

	@Id
	@Column(columnDefinition = "INT")
	private int id;

	@Basic
	@Column(nullable = false, length = 128)
	private String password;

	@ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.MERGE)
	@JoinColumn(name = "role_id", columnDefinition = "INT", nullable = false)
	private Role role;

	@Basic
	@Column(nullable = false, length = 32)
	private String username;

	public User() {
	}

	public User(int id, String email, String username, boolean enabled, String password) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.email = email;
		this.enabled = enabled;

	}

	public User(int id) {
		this.id = id;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public boolean isEnabled() {
		return enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
}